"""Create opaque, database-backed rate-limit buckets.

No client IP address, email address, device token, or session token is stored.
The primary key is a keyed blind index generated by the application.
"""

from alembic import op
import sqlalchemy as sa


revision = "0014_centralized_rate_limits"
down_revision = "0013_input_explanation_limit"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("rate_limit_buckets"):
        op.create_table(
            "rate_limit_buckets",
            sa.Column("key_hash", sa.String(length=64), primary_key=True),
            sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("request_count", sa.Integer(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        )
    indexes = {index["name"] for index in inspector.get_indexes("rate_limit_buckets")}
    if "ix_rate_limit_buckets_window_started_at" not in indexes:
        op.create_index("ix_rate_limit_buckets_window_started_at", "rate_limit_buckets", ["window_started_at"])


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("rate_limit_buckets"):
        indexes = {index["name"] for index in inspector.get_indexes("rate_limit_buckets")}
        if "ix_rate_limit_buckets_window_started_at" in indexes:
            op.drop_index("ix_rate_limit_buckets_window_started_at", table_name="rate_limit_buckets")
        op.drop_table("rate_limit_buckets")
