"""Rebrand only legacy autogenerated account display-name placeholders.

User-entered names are never changed by this migration.
"""

from alembic import op
import sqlalchemy as sa


revision = "0015_signalam_brand_placeholders"
down_revision = "0014_centralized_rate_limits"
branch_labels = None
depends_on = None


def upgrade() -> None:
    users = sa.table(
        "users",
        sa.column("first_name", sa.String()),
        sa.column("last_name", sa.String()),
    )
    op.execute(
        users.update()
        .where(users.c.first_name == "BantAI")
        .where(users.c.last_name.in_(("User", "Administrator")))
        .values(first_name="Signalam")
    )


def downgrade() -> None:
    # Reversing a display-name cleanup could overwrite a user's later edit.
    pass
